---
# tasks file for ansible-role-openvpn-debian

- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Set openvpn configurations
  command: "/usr/local/openvpn_as/scripts/sacli --key {{ item.key }} --value {{ item.value }} ConfigPut"
  environment:
    public_hostname: "{{ openvpn_hostname }}"
    admin_user: "{{ openvpn_admin_username }}"
    admin_pw: "{{ openvpn_admin_password }}"
    reroute_gw: '1'
    reroute_dns: '1'
  with_items:
    - { key: vpn.client.tls_version_min, value: 1.2 }
    - { key: vpn.client.tls_version_min_strict, value: true}
    - { key: vpn.server.tls_version_min, value: 1.2 }
    - { key: cs.tls_version_min, value: 1.2 }
    - { key: cs.tls_version_min_strict, value: true }
    - { key: vpn.client.config_text, value: "'cipher AES-256-CBC'" }
    - { key: vpn.server.config_text, value: "'cipher AES-256-CBC'" }

- name: Restart and set username
  command: "{{ item }}"
  with_items:
    - "/usr/local/openvpn_as/scripts/sacli start"
    - "/usr/local/openvpn_as/scripts/ovpnpasswd -u {{ openvpn_admin_username }} -p {{ openvpn_admin_password }}"